name: 'Check for Pending Tasks in Github'
description: 'Sends emails to users in case there are "Open" Issues or Pull Requests assigned to them, via Sendgrid'
inputs:
  sendgrid-from-email:
    description: 'Validated Sendgrid Email'
    required: true
  email-subject:
    description: 'Email subject'
    required: false
    default: 'Check out these Github tasks assigned to you that are still pending'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "bell"
  color: yellow
